name: Attend_my

on:
  workflow_dispatch:
  schedule:
    - cron: '30 23 * * *'
  repository_dispatch:
    types: joy

jobs:
  Run1:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: HibariX/AutoAttendYuKeTang
          ref: master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        run: yarn

      - name: Run
        run: node src/index.js
        env:
          USER_INFO: ${{ secrets.USER_INFO }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_ID: ${{ secrets.BARK_ID }}
  Run2:
    runs-on: macos-latest
    needs: Run1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: HibariX/AutoAttendYuKeTang
          ref: master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        run: yarn

      - name: Run
        run: node src/index.js
        env:
          USER_INFO: ${{ secrets.USER_INFO }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_ID: ${{ secrets.BARK_ID }}
  Run3:
    runs-on: macos-latest
    needs: Run2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: HibariX/AutoAttendYuKeTang
          ref: master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        run: yarn

      - name: Run
        run: node src/index.js
        env:
          USER_INFO: ${{ secrets.USER_INFO }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_ID: ${{ secrets.BARK_ID }}





